---
- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.status == "enabled"

- name: Reboot system's after SELinux policy disabled
  shell: sleep 3 && reboot now
  async: 1
  poll: 0
  when: ansible_selinux.status == "enabled"

- name: Wait when my servers is come back after reboot
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    delay: 5
    timeout: 120
  delegate_to: 127.0.0.1
  when: ansible_selinux.status == "enabled"


